spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://shoppingmall-deploy.cloudtype.io:5433/shoppingdb
    username: shopping
    password: shopping123


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # 또는 create / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  address: 0.0.0.0
  port: 8080
