server:
  address: 0.0.0.0
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  profiles:
    active: local

  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoppingdb
    username: postgres
    password: postgres123

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html        # Swagger UI 접속 경로
    operations-sorter: method     # GET, POST, PUT 순서 정렬
    tags-sorter: alpha            # 태그 알파벳순 정렬
  api-docs:
    path: /v3/api-docs            # API 문서 JSON 경로
  default-produces-media-type: application/json
  default-consumes-media-type: application/json


jwt:
  secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32CHARS"
  access-token-validity-ms: 3600000  # 1시간